import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground overflow-hidden w-screen h-screen">
        {/* pwa setup screen */}
        <div className="max-w-md bg-white/20  w-full h-full mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
